* Racket 第五课

** 昨日复习

除了前几天学习的内容，还有很多Racket知识没有学习，比如：读写文件、正则表达式、合同等。
这些知识可以在做小项目中学习。

首先学习了计算的本质 -> 学习LISP。

- 最初的语言使用 MACHINE CODE ，ASSEMBLY CODE（汇编）
- Fortune、C语言引入了函数
- C++/JAVA 引入了 TYPE（Class） ，在LISP中引入 CLOSEURE （闭包）

LISP中 CLOSEURE 就是 lambda表达式（λ-exp），define 绑定 key-value （键值对）,cons 函数创造 PAIR （偶对）。
通过 alist （属于PROPER LIST）存储多个偶对，可以构成一个数据库，通过assoc函数可以对其进行操作。

REPL 求值过程中，两个公式：(eval exp env)、(apply proc arg)， apply 用于在求值过程中构造临时表达式。

三种求值器的变形： STREAM 、 回溯 、 逻辑运算。

。。。。。。

** 人工智能导论

人工智能（AI）分为4个部分介绍。

- AI 简介
- AI ETHODOCOGY 人工智能方法论
- LISP与AI的关系
- AI的方向 CASE STUDIES

*** 一 AI 简介

人脑中有10的12次方个神经元，而其中的大部分都没有被开发。

人有八识：

- 五官
- 六识 由记忆组成
- 七识 末那（梵语：manas） 比如：一眼认出老朋友，这是一种模式识别。
- 八识 Alaye 指识之本体，人的潜能，人能调用另一个自己对自己产生认识。

AI指让计算机模拟人的某方面能力。

*** 二 AI ETHODOCOGY

AI问题解题的方法论，分为三个共同特点：

- TARGET 问题的目标
- STATE 求解的过程、状态的变化、问题的转化
- OPERATE 操作

这三点是解决所有AI问题所共同拥有的方面。

举个例子：一个老虎妈妈带着两个虎孩子和一个豹子要过河，豹子不能和虎孩子单独待在一起。
而过河的小船只能坐两只动物，并且只有虎妈妈才能划船，请问，它们该如何过河？

对于这个问题，就是排列组合（COMRINATION AERMMCATION），尝试找到成功的排列。

把人工智能可以分为3个层次，最底层是

- 查找与排序 SEARCH & SORT

但是当基数太大时，要避免组合爆炸。因此组合的复杂度不能是n的阶乘那样，几何增加，可以是n的平方、n的次方。

 查找与排序 中，关键是降低复杂度，对问题空间进行聚类，商化。

第二层是：

- 建立模式 PATTERN 这是AI的核心。

最上层就是应用：

- 应用 如：下棋、证明、机器学习、自然语言、图像识别等。

*** 三 LISP与AI的关系

在 PM 1 2 3 理论中，可以通过集合、图（网）、矩阵来解决问题。

解决问题的模型如下：

#+BEGIN_SRC
+-----------+
|           | <--- 构造解题空间
|  +-----+  |
|  |o o o|<-+----- 问题空间
|  | o o |  |
|  +-----+  |
|           |
+-----------+
#+END_SRC

如果用图，则可以把图进行商化，对子问题进行求解。
商化的子集里是个偏序结构。
问题组成一个TREE树结构，而TREE是LIST的嵌套，所以用LSIP语言来处理AI问题。

*** 四 CAE STUDIES

**** 自然语言处理

对语言的处理不像处理数字那么简单。

比如： I READ A BOOK ==》 (READ I A.BOOK)

BOOK还有一些属性，如：
(BOOK ATTRIBUTES ((LENGTH THICK) (DIFFICUTY DIFF) (TOPIC A)))

这些属性是内节点。

如果这本书是我十年前读过的，那么这个描述是外节点：(READ I 10-YEARS-AGO)。

处理结构如下：

#+BEGIN_SRC
        +
        |
 +---------------+
 |      |        |
 v      v        v
READ    I    BOOK(...)    <-- 内属性（PROPERTY）
                 +
                 |
          +------+---------+   <-- 外属性（PROPERTY）
          |      |         |
          v      v         v
         READ    I    10-YEARS-AGO
#+END_SRC

老的LISP里面有 PLIST 来存储这些数据，而Racket里面没有 PLIST 取而代之的是 ALIST。

**** 图像识别 GRAPH RECONGITION

人眼就像两个 SENSORS （传感器），传递 SIGNALS （信号）给大脑。如果是用计算机处理这些信号，需要 A/D 转换。

比如人识别桌子的边角，大脑里面有对应的模式能够识别。如果用计算机处理，我们需要找到特征值。
可以把它变成线性代数问题，从而转化问题，解决问题。

**** 机器学习 MACHINE LEARNTING

机器学习就是通过给予样本，让计算机自己学习，从中发现规律。

这就是一个不断积累的过程，把经验存放在集合里。
